<a href="https://colab.research.google.com/github/Labani4321/AI-ML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy, short for Numerical Python, is a powerful Python library used primarily for numerical computing and data analysis. It provides support for arrays, matrices, and a wide range of mathematical functions to operate on these data structures efficiently.


In [1]:
import numpy as np


In [2]:
import platform
print('Python version: '+platform.python_version())
print('Numpy Version: '+np.__version__)

Python version: 3.10.12
Numpy Version: 1.26.4


A NumPy array is a central data structure in the NumPy library, designed for efficient numerical computing in Python. It is a grid of elements of the same data type, indexed by a tuple of non-negative integers. NumPy arrays are homogeneous, meaning that all elements must be of the same data type. This allows for fast and memory-efficient operations on large datasets.

In [3]:
# create an array with a specified data type
arr = np.array([1,2,3], dtype='f4')
print(arr)
print(arr.dtype)

arr = np.array([1+2j, 3-4j], dtype=np.complex64)
print(arr)
print(arr.dtype)



[1. 2. 3.]
float32
[1.+2.j 3.-4.j]
complex64


# 1. Create **Arrays**

In [4]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [7]:
arr = np.random.rand(3, 3)
print(arr)

[[0.13843116 0.61343361 0.85235734]
 [0.39145627 0.0450953  0.24090274]
 [0.85858721 0.6164459  0.98015149]]


In [8]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# **Inspect an Array**

In [9]:
arr = np.array([[1,2,3], [4,5,6]], dtype=np.int64)

In [10]:
print(arr.dtype)

int64


In [11]:
print(arr.shape)

(2, 3)


In [12]:
print(arr.ndim)

2


In [13]:
print(arr.itemsize)

8


In [14]:
# arr.nbytes = arr.size * arr.itemsize
print(arr.nbytes)

48


 **Generate a random sample from interval [0, 1) in a given shape**

In [15]:
# generate a random scalar
print(np.random.rand())

0.8485124736624194


In [16]:
# generate a 1-D array
print(np.random.rand(3))

[0.84276031 0.35520517 0.5693528 ]


In [17]:
# generate a 2-D array
print(np.random.rand(3,3))

[[0.4315945  0.44629063 0.46198255]
 [0.17779991 0.90015807 0.75932666]
 [0.5320616  0.4706491  0.00298253]]


In [18]:
print(np.random.randn(3,3))

[[-0.66860499  0.5170326  -0.20217829]
 [-0.57698221 -2.41363138 -0.46524503]
 [-0.50278286  0.72854891 -0.11099536]]


In [19]:
# np.random.randint(low, high, size, dtype)
print(np.random.randint(1, 10, 3, 'i8'))

[4 3 6]


In [20]:
# the following methods are the same as np.random.rand()
print(np.random.random_sample(10))
print(np.random.random(10))
print(np.random.ranf(10))
print(np.random.sample(10))

[0.54915012 0.59262722 0.03777703 0.07511752 0.9333705  0.06186206
 0.48771443 0.52524979 0.5869351  0.2436565 ]
[0.30968577 0.92810267 0.99134138 0.73762153 0.08076704 0.51053113
 0.8514029  0.50688944 0.06618101 0.61082703]
[0.95152458 0.0854133  0.25964742 0.12252634 0.2987154  0.6420781
 0.34092974 0.27385405 0.51024258 0.24059324]
[0.71507022 0.66515655 0.5265822  0.45706794 0.02361786 0.02549716
 0.40353953 0.9863427  0.94236393 0.05162386]


In [21]:
# it returns a copy rather than making changes in place
arr = np.array(range(10))
print('The initial array: ', arr)
print('A permutation of the array: ', np.random.permutation(arr))

The initial array:  [0 1 2 3 4 5 6 7 8 9]
A permutation of the array:  [2 7 6 0 9 1 4 3 8 5]


In [22]:
arr1 = np.array([1,2,3])
# the above operations can be performed using numpy built-in functions
# which can save memory as the output can be stored in the original array rather than assigning new memoryarr = np.array([1,2,3])

np.add(arr1, [8,9,10], out=arr1)
print(arr1)

np.subtract(arr1, [8,9,10], out=arr1)
print(arr1)

np.multiply(arr1, [1,2,3], out=arr1)
print(arr1)

[ 9 11 13]
[1 2 3]
[1 4 9]


In [23]:
arr = np.random.rand(5,5)

In [24]:
print(arr)

[[0.02469739 0.52521997 0.31803104 0.72670911 0.19233633]
 [0.44761209 0.91376666 0.70747905 0.61744398 0.27783058]
 [0.23428439 0.94483085 0.26850965 0.73819331 0.06230251]
 [0.47471083 0.74217531 0.73691745 0.04291194 0.39567567]
 [0.2419205  0.13909471 0.73554411 0.64751875 0.43507364]]


In [25]:
# sum along the row
print(np.sum(arr, axis=0))

[1.42322519 3.26508749 2.7664813  2.77277708 1.36321871]


In [26]:
# calculate min along the row
print(np.min(arr, axis=0))

[0.02469739 0.13909471 0.26850965 0.04291194 0.06230251]


In [27]:
# calculate max along the column
print(np.max(arr, axis=1))

[0.72670911 0.91376666 0.94483085 0.74217531 0.73554411]


In [28]:
# compute the overall mean
print(np.mean(arr))

0.4636315911636759


In [29]:
# compute the overall median
print(np.median(arr))

0.44761208951994347


In [30]:
# compute the overall standard deviation
print(np.std(arr))

0.27105168822158116


In [31]:
# compute the overall variance
print(np.var(arr))

0.07346901768776923


In [32]:
# calculate the cumulative sums along the row
print(np.cumsum(arr, axis=0))

[[0.02469739 0.52521997 0.31803104 0.72670911 0.19233633]
 [0.47230948 1.43898663 1.0255101  1.34415309 0.47016691]
 [0.70659387 2.38381747 1.29401975 2.08234639 0.53246941]
 [1.18130469 3.12599278 2.03093719 2.12525834 0.92814508]
 [1.42322519 3.26508749 2.7664813  2.77277708 1.36321871]]


In [33]:
# calculate the cumulative product along the row
print(np.cumprod(arr, axis=0))

[[2.46973895e-02 5.25219965e-01 3.18031042e-01 7.26709110e-01
  1.92336332e-01]
 [1.10548501e-02 4.79928494e-01 2.25000301e-01 4.48702163e-01
  5.34369138e-02]
 [2.58997880e-03 4.53451246e-01 6.04147526e-02 3.31228933e-01
  3.32925364e-03]
 [1.22949097e-03 3.36540317e-01 4.45206852e-02 1.42136770e-02
  1.31730465e-03]
 [2.97439069e-04 4.68109764e-02 3.27469277e-02 9.20362232e-03
  5.73124523e-04]]


In [34]:
arr = np.random.rand(3,4)

In [35]:
print(arr)

[[0.80244372 0.58617876 0.67559659 0.4713609 ]
 [0.73278709 0.18451069 0.58575049 0.21947135]
 [0.83518199 0.25532918 0.07161056 0.2467805 ]]


# **Manipulate an Array**



In [36]:
# the following methods return a copy
print(arr.T)
# or
print("")
print(np.transpose(arr))
# or
print("")
print(arr.transpose())

[[0.80244372 0.73278709 0.83518199]
 [0.58617876 0.18451069 0.25532918]
 [0.67559659 0.58575049 0.07161056]
 [0.4713609  0.21947135 0.2467805 ]]

[[0.80244372 0.73278709 0.83518199]
 [0.58617876 0.18451069 0.25532918]
 [0.67559659 0.58575049 0.07161056]
 [0.4713609  0.21947135 0.2467805 ]]

[[0.80244372 0.73278709 0.83518199]
 [0.58617876 0.18451069 0.25532918]
 [0.67559659 0.58575049 0.07161056]
 [0.4713609  0.21947135 0.2467805 ]]


In [37]:
arr = np.array([1,2,3])

In [38]:
# append a scalar and return a copy
arr1 = np.append(arr, 4)
print(arr1)

[1 2 3 4]


In [39]:
# np.insert(array, position, element)

# insert a scalar at a certain position
arr3 = np.insert(arr, 0, 100)
print(arr3)

[100   1   2   3]


In [40]:
# remove the element at position 0
arr4 = np.delete(arr, 0)
print(arr4)

[2 3]


In [41]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

In [42]:
# concat along the row
cat = np.concatenate((arr1, arr2), axis=0)
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [43]:
# concat along the column
cat = np.concatenate((arr1, arr2), axis=1)
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [44]:
arr1 = np.random.rand(5,5)
arr2 = np.random.rand(5,5)

In [45]:
print(arr1.dot(arr2))
# or
print(np.dot(arr1, arr2))
# or
print(arr1 @ arr2)

[[0.7571696  1.29685604 1.16514373 1.12468873 1.28519863]
 [0.26087538 0.72385642 0.47716703 0.34409519 0.58530877]
 [0.19070449 0.63639778 0.56352997 0.41604066 0.2174662 ]
 [0.84886254 1.34551518 0.74550046 0.94797861 1.01127096]
 [1.04856987 1.65327146 0.53067896 1.09272101 1.06257927]]
[[0.7571696  1.29685604 1.16514373 1.12468873 1.28519863]
 [0.26087538 0.72385642 0.47716703 0.34409519 0.58530877]
 [0.19070449 0.63639778 0.56352997 0.41604066 0.2174662 ]
 [0.84886254 1.34551518 0.74550046 0.94797861 1.01127096]
 [1.04856987 1.65327146 0.53067896 1.09272101 1.06257927]]
[[0.7571696  1.29685604 1.16514373 1.12468873 1.28519863]
 [0.26087538 0.72385642 0.47716703 0.34409519 0.58530877]
 [0.19070449 0.63639778 0.56352997 0.41604066 0.2174662 ]
 [0.84886254 1.34551518 0.74550046 0.94797861 1.01127096]
 [1.04856987 1.65327146 0.53067896 1.09272101 1.06257927]]


In [46]:
arr = np.random.rand(5,5)

In [47]:
print(arr)

[[0.13375822 0.4148011  0.40631434 0.29235348 0.38018126]
 [0.3296828  0.9847537  0.92729495 0.1074607  0.14354003]
 [0.60234021 0.12842497 0.26508889 0.31163316 0.14015382]
 [0.68423402 0.38327388 0.4666037  0.53700524 0.38732231]
 [0.73842548 0.22747965 0.7233531  0.53577907 0.30256489]]


In [48]:
# compute the inverse of a matrix
print(np.linalg.inv(arr))

[[  4.75299699  -0.23591746  11.11019646  -7.19264519  -1.79928793]
 [ -3.77801585   1.15922758  -5.04032039   6.37529664  -1.62920151]
 [  1.77938602   0.13942928   1.2854365   -4.14215242   2.40505861]
 [-16.16277359   0.7004139  -26.56730118  22.62117176   3.32513986]
 [ 15.60735963  -1.86940703  20.64647223 -17.39372122  -2.71676164]]


In [49]:
import numpy as np
import time

# Define the size of the array/list
size = 1000000

# Create a Python list
start_time = time.time()
py_list = list(range(size))
py_list_sum = sum(py_list)
end_time = time.time()
py_time = end_time - start_time

# Create a NumPy array
start_time = time.time()
np_array = np.arange(size)
np_array_sum = np.sum(np_array)
end_time = time.time()
np_time = end_time - start_time



print("Time taken for NumPy array operation:", np_time)
print("Time taken for Python list operation:", py_time)


Time taken for NumPy array operation: 0.010814189910888672
Time taken for Python list operation: 0.16726064682006836
